gamedig/rust-gamedig

src/socket.rs

In the first test `test_tcp_socket_send_and_receive()`, a TCP socket is created, and a message is sent to a server that is running in a separate thread. The server receives the message, echoes it back to the client, and the client receives the response. The function `TcpSocket::new()` is used to create the TCP socket, and the `send()` and `receive()` methods are used to send and receive messages over the socket.
In the second test `test_udp_socket_send_and_receive()`, a similar process occurs with a UDP socket. The `UdpSocket::new()` method is used to create the UDP socket, and the `send()` and `receive()` methods are used to send and receive messages over the socket.
Both tests make use of the `std::thread` module to spawn a separate thread to run the server, and the `net` module to bind …

Test: udp and tcp socket test

---

.pre-commit-config.yaml

These hooks can be installed using [pre-commit], with: "pre-commit install". Once installed they will prevent you from committing if the staged code has clippy warnings or hasn't been formatted. You can skip the pre-commit checks by adding the "-n" flag to your git commit command.
The hooks also require rustup as the nightly versions of rustfmt and clippy are used.
[pre-commit]: https://pre-commit.com/

[PreCommit] Add clippy and rustfmt pre-commit hooks

---

.github/workflows/ci.yml

Pins a specific nightly version to fix errors in CI regarding version mismatch.
Also reorders the check flow to move formatting to the 2nd last place.

[CI] Pin specific rustfmt version

---

examples/generic.rs
src/games/mod.rs

Allow passing through timeout options when doing a generic game query (except on proprietary games).

[Games] Add method to query with timeout options

---

src/games/ffow.rs
src/games/jc2mp.rs
src/games/mod.rs
src/games/ts.rs

Adding query functions with timeout settings to proprietary games allows the generic query with timeout function to pass the timeout settings through.
This does change how the pre-existing FFOW query_with_timeout function worked: it accepted a non-optional timeout settings, this was changed to optional to be consistent with other query_with_timeout functions and to move deciding what to do if the user doesn't provide timeout settings to a more central location.
Closes #64

[Games] Add timeout settings for proprietary games

---

.github/workflows/ci.yml
.pre-commit-config.yaml
Cargo.toml
README.md
VERSIONS.md
src/buffer.rs
src/errors.rs
src/games/bat1944.rs
src/games/jc2mp.rs
src/games/mc.rs
src/protocols/gamespy/common.rs
src/protocols/gamespy/protocols/one/protocol.rs
src/protocols/gamespy/protocols/three/protocol.rs
src/protocols/gamespy/protocols/two/protocol.rs
src/protocols/minecraft/protocol/bedrock.rs
src/protocols/minecraft/protocol/java.rs
src/protocols/minecraft/protocol/legacy_bv1_8.rs
src/protocols/minecraft/protocol/legacy_v1_4.rs
src/protocols/minecraft/protocol/legacy_v1_6.rs
src/protocols/minecraft/protocol/mod.rs
src/protocols/minecraft/types.rs
src/protocols/quake/client.rs
src/protocols/quake/one.rs
src/protocols/quake/two.rs
src/protocols/types.rs
src/protocols/valve/protocol.rs
src/protocols/valve/types.rs
src/services/valve_master_server/service.rs
src/socket.rs
src/utils.rs

A first draft of implementing a better error type that propagates source errors and messages.
Requires bumping MSRV to 1.65.0 as it uses [backtraces](https://doc.rust-lang.org/std/backtrace/index.html).
I didn't rename `GDError` as that would require a lot more changes throughout the codebase, however I changed `GDResult` to use the new `GDRichError` (which uses `GDError` as its kind part) and added a From implementation so `GDError`s that are not updated are implicitly converted to the new `GDRichError` (with an added backtrace).
Other than that its a pretty basic type but has a custom debug formatter so an unwrapped error output looks like this:
```
$ RUST_BACKTRACE=1 cargo run --example generic mc-java mc.hypixel.net
Querying 209.222.115.42 with game Game {
name: "Minecraft (java)", …
```

Add rich error type

---

.pre-commit-config.yaml
CHANGELOG.md
examples/generic.rs
src/games/mod.rs
src/protocols/minecraft/protocol/mod.rs
src/protocols/minecraft/types.rs
src/protocols/mod.rs
src/protocols/types.rs
src/protocols/valve/types.rs

Adds a new struct `ExtraRequestSettings` that contains all possible
extra settings for all protocols, and can be implicitly converted with
`.into()` into each protocol's extra settings type.
This is then used in a new query method
`query_with_timeout_and_extra_settings()` that passes the object on to
the selected protocol.
This also updates the generic example to set some of these generic
settings so that it can be used for certain queries like
"mc.hypixel.net".
Closes #86

[Generic] Add struct for all extra request settings

---

.github/workflows/ci.yml

This should save us a few actions minutes with all the CI PRs lately :).

[CI] Only run build checks when a rust related file has changed

---

.github/labeler.yml
.github/workflows/labeler.yml

It's the `game` tag, not `games`.
Adds `labeler.yml` as file for CI tag.
Also uses checkout to avoid `The configuration file (path: .github/labeler.yml) isn't not found locally, fetching via the api` warning.

[CI] Fix misc stuff with labeler CI

---

.github/badges/node.svg
.github/workflows/node-badge.yml
README.md

Adds a badge to README that shows what percentage of games supported by node-gamedig are supported by us (it doesn't check whether we have a game but use the wrong name for it: it works by checking whether the game ID from node-gamedig exists in are game definitions file). And CI that should automatically update this badge.

[CI] Add node comparison badge

---

src/protocols/gamespy/protocols/one/protocol.rs
src/protocols/gamespy/protocols/one/types.rs

This fixes the "playername" field being filtered out, which would cause parsing to fail for some `bf1942` servers which use that field instead of "player".
It also makes more fields on the Gamespy1 Player type optional, this is because in my testing I saw some servers (`bf1942`) not providing them so as a result the parse would fail if these were not optional.
This is taken from #92 but is just partial work on #88, it might not solve all issues, but they are the obvious fixes that should help us in narrowing down the other ones.

[Protocol] Make gamespy1 parsing less likely to fail

---

src/games/definitions.rs

`minecraftping` is the same as `minecraft`, this has been added here to match node-gamedig's id definitions in #100.
There were 2 query methods and the `minecraftping` became the standard `minecraft`, it is being kept there for id backwards compatibility reasons, in [9b92771](https://github.com/gamedig/node-gamedig/commit/9b9277172dc6011bafdc12fe2b99b262129adf28) shows that at some point, this id was marked as "Legacy name".

Remove `minecraftping` from game definitions as its useless

---

CHANGELOG.md
src/errors/error.rs
src/errors/kind.rs

While working on a personal project, I use juniper subscriptions and I have a stream that inside it calls valve queries.
Before I was on version `0.2.3` and when I tried to upgrade to `0.4.0` I encountered several async problems regarding the error type which came from the stacktracing rework from #80.
This PR adds Send and Sync to the error source type, although I dont know much async rust, I do not know the consequences of doing these (until #37 will come into play at least), thus the request of reviews.

Add Send and Sync on Error Source

---

CHANGELOG.md
GAMES.md
examples/generic.rs
src/games/definitions.rs
src/games/mod.rs
src/games/valve.rs
src/protocols/valve/mod.rs
src/protocols/valve/types.rs

This PR aims to add an optional additional parameter on the `game_query_mod` and `game` macros regarding specifying `GatheringSettings` as some games don't respond to certain A2S queries (I have also added support for Valheim to show this (it does not respond to rules but does on players)).
Still need to be done to merge this:

feat: Add GatheringSettings on Valve macros

---

src/protocols/gamespy/mod.rs
src/protocols/quake/mod.rs
src/protocols/valve/mod.rs

These macros are only required when compiling the code gated behind the games feature, they are unused if that feature is not and are also crate only.

protocols: Only compile game impl macros when they are needed

---

CHANGELOG.md
crates/lib/examples/generic.rs
crates/lib/examples/valve_protocol_query.rs
crates/lib/src/games/minecraft/protocol/bedrock.rs
crates/lib/src/games/minecraft/protocol/java.rs
crates/lib/src/games/minecraft/protocol/legacy_v1_4.rs
crates/lib/src/games/minecraft/protocol/legacy_v1_6.rs
crates/lib/src/games/minecraft/protocol/legacy_vb1_8.rs
crates/lib/src/protocols/gamespy/protocols/one/protocol.rs
crates/lib/src/protocols/gamespy/protocols/three/protocol.rs
crates/lib/src/protocols/gamespy/protocols/two/protocol.rs
crates/lib/src/protocols/quake/client.rs
crates/lib/src/protocols/types.rs
crates/lib/src/protocols/unreal2/protocol.rs
crates/lib/src/protocols/valve/protocol.rs
crates/lib/src/services/valve_master_server/service.rs
crates/lib/src/socket.rs

Because TcpSocket connects in Socket::new TimeoutSettings are now required for Socket::new. Since we already have TimeoutSettings there Sockets are now expected to apply timeout settings in Socket::new.
This fixes hanging when TCP cannot make a connection.

protocols: Add connect timeout to TimeoutSettings

---

.github/badges/node.svg
.github/workflows/node-badge.yml
.github/workflows/scripts/node-badge.mjs

Fixes #155 using a new node script that should be more robust than the
old shell script.

ci: Update node coverage badge to work without games.txt

---

CHANGELOG.md
crates/cli/Cargo.toml
crates/cli/src/error.rs
crates/cli/src/main.rs
crates/lib/Cargo.toml
crates/lib/src/games/minecraft/types.rs
crates/lib/src/protocols/gamespy/mod.rs
crates/lib/src/protocols/quake/types.rs
crates/lib/src/protocols/types.rs

There was a bunch of things I wanted to add to the CLI so I put them in one PR.
- Added DNS lookup support
- Added JSON output option (and output the original response struct by default)
- Added ExtraRequestSettings as CLI arguments
- Added TimeoutSettings as CLI argument
If there's any that need more work or we don't want I can remove/split into other PR.
NOTE whichever of this or #158 gets merged first will cause issue with clap args.

Various improvements for the CLI

---

.github/workflows/labeler.yml

This reverts commit 04da29f2a6b11157524c170097db14232ef32813.
I tried to update the config in #166 but there seems to be a bug.
EDIT: This still used v5 in CI (maybe the config doesn't update until in main?)

Revert "Bump actions/labeler from 4 to 5 in /.github/workflows (#165)"

---

CHANGELOG.md
crates/lib/src/games/jc2m/mod.rs
crates/lib/src/games/jc2m/protocol.rs
crates/lib/src/games/jc2m/types.rs

While making #135 I've seen that having everything of a proprietary protocol in a single file was being a bit too cluttered and I've extracted stuff into multiple files (`types` and `protocol`).
This would also apply for `FFOW` and `The Ship`, but I've decided to take some opinions on it.
This PR also makes all of jc2m's `response` and `player` fields public.

chore: extract jc2m into multiple files

---

CHANGELOG.md
crates/lib/src/buffer.rs
crates/lib/src/games/definitions.rs
crates/lib/src/games/mindustry/mod.rs
crates/lib/src/games/mindustry/protocol.rs
crates/lib/src/games/mindustry/types.rs
crates/lib/src/games/mod.rs
crates/lib/src/games/query.rs
crates/lib/src/protocols/types.rs

Adds support for mindustry.
Also changes:
- Adds UTF8LengthPrefixed string decoder to buffer.rs
- `game!` macro now uses expressions for default port allowing it to reference a constant value.

Add support for Mindustry

---

.pre-commit-config.yaml
crates/cli/Cargo.toml
crates/id-tests/src/lib.rs
crates/id-tests/src/main.rs
crates/lib/Cargo.toml

- Set default binary to gamedig cli so that `cargo run` runs the CLI.
- Use the correct option to disable default features when depending on gamedig-id-tests
- Run pre-commit CI when Cargo.toml gets changed
- Clippy fixes in ID test library

fix: various crate/clippy/ci changes

---

.github/badges/node.svg
CHANGELOG.md
crates/lib/Cargo.toml
crates/lib/examples/test_eco.rs
crates/lib/src/errors/kind.rs
crates/lib/src/games/definitions.rs
crates/lib/src/games/eco/mod.rs
crates/lib/src/games/eco/protocol.rs
crates/lib/src/games/eco/types.rs
crates/lib/src/games/mod.rs
crates/lib/src/games/query.rs
crates/lib/src/http.rs
crates/lib/src/lib.rs
crates/lib/src/protocols/types.rs

A lot of games that have a proprietary protocol hosts their query capabilities via a simple http server, on a GET query.
In this (unfinished, concept) PR, I have attempted on adding [Eco](https://store.steampowered.com/app/382310/Eco/), a game that provides its query information on its ip and port (+1 for query) and `/frontpage`, resulting in `http://{ip}:{port}/frontpage`.
I added HTTP support via [Reqwest](https://github.com/seanmonstar/reqwest), as I find it easy to use and provides a blocking API (supports async for future use). 
I thought initially on using [Hyper](https://github.com/hyperium/hyper), but I find it quite complicated compared to Reqwest.
Some caviats:
* Reqwest doesn't support separate read and write timeouts, they group these 2 as one timeout setting.
* * I for one …

feat: http client and eco support

---

GAMES.md
crates/lib/CHANGELOG.md
crates/lib/src/games/definitions.rs
crates/lib/src/games/valve.rs

Yet another Valve-protocol game, Soulmask, [added in Node-GameDig](https://github.com/gamedig/node-gamedig/pull/572) by @xCausxn.

feat: add Soulmask support

---

crates/lib/src/games/battalion1944.rs
crates/lib/src/games/definitions.rs
crates/lib/src/games/minecraft/mod.rs
crates/lib/src/lib.rs
crates/lib/src/protocols/epic/protocol.rs

Applied [assigning_clones](https://rust-lang.github.io/rust-clippy/master/index.html#/assigning_clones) which could help performance.
And[redundant_static_lifetimes](https://rust-lang.github.io/rust-clippy/master/index.html#/redundant_static_lifetimes) which just cleans up obvious a lifetime.
I also have sorted out some unused imports warnings, see below comment.

chore: apply clippy suggestions

---

crates/cli/CHANGELOG.md
crates/cli/Cargo.toml
crates/cli/README.md

This is the `v0.1.1` patch for gamedig-cli, its mainly dependency updates. Details can be found in changelog.

CLI dep patch

---

crates/cli/.cargo/config.toml

This PR adds an explicit configuration for the CLI crate to optimize release builds within the CI pipeline.
Unsure if this is worthy of a patch, I think its okay for now it can just be included in next release when built by CI.

Fix CLI release profile

---

crates/lib/src/buffer.rs

Adds a out of bounds check and error handling on read string within buffer to handle a panic that may occur.

Fix: read string may panic index out of range

---

crates/lib/src/socket.rs

This PR adds a capture feature gate to local_addr to resolve a unused var warning with clippy

Fix: Unused var in most features

---

crates/lib/src/protocols/epic/protocol.rs

This follows the same method as node to try and match ports on epic query's.

Fix: try to match port on epic protocol

---

.github/workflows/audit.yml

https://github.com/gamedig/rust-gamedig/pull/227 fails to get through because of audit check v2 which [removed the auto generation of it](https://github.com/rustsec/audit-check/pull/20), this is [intended](https://github.com/rustsec/audit-check/issues/27).

ci: fix audit failing by generating cargo lock file before running it

---

crates/lib/src/games/definitions.rs
crates/lib/src/games/valve.rs
crates/lib/src/protocols/valve/types.rs

for some reason Starbound returns the server type and environment in uppercase, so I'm converting to lowercase to work around that.

Add Starbound support
