- src/bufferer.rs
- src/lib.rs
- src/protocols/valve/protocol.rs
- src/protocols/valve/types.rs
> Chore: clippy

- Cargo.toml
- src/games/ts.rs
- src/protocols/gamespy/types.rs
- src/protocols/minecraft/types.rs
- src/protocols/valve/types.rs
This adds support for the Serde serialization and deserialization framework as a new feature. I have also implemented additional built-in derives for additional functionality.
> Feature: serde

- CHANGELOG.md
- SERVICES.md
- examples/valve_master_server_query.rs
- src/lib.rs
- src/services/mod.rs
- src/services/valve_master_server/mod.rs
- src/services/valve_master_server/service.rs
- src/services/valve_master_server/types.rs
> [Service] Add valve master server query

- .pre-commit-config.yaml
- README.md
- VERSIONS.md
VERSIONS.md tells you what the current versions for things like MSRV is and which files you need to update if you change it.
Also fixes the incorrect:
- MSRV in README.md
- nightly version in .pre-commit-config.yaml
> [Crate] Add documentation for where versions need to be updated

- Cargo.toml
- src/lib.rs
- src/protocols/types.rs
Positive features are more useful as far as I know.
> [Crate] Swap no_games, no_services for games, services

- .github/workflows/audit.yml
- .github/workflows/ci.yml
- Cargo.toml
> [CI] Using recommended CI Cargo audit Github action and update serde

- examples/generic.rs
- Allow entering DNS names that can be resolved
- Output a list of games if there is no game provided
> [Example] Improve generic example

- .github/workflows/ci.yml
- .pre-commit-config.yaml
> Add rustdoc checks to CI and tests to pre-commit

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/help-regarding-code-protocol-errors.md
> [Crate] Update issue templates

- src/protocols/valve/protocol.rs
- src/protocols/valve/types.rs
> Add app id checking to valve protocol in gather settings

- examples/master_querant.rs
- examples/minecraft.rs
- src/games/mc.rs
- src/games/mod.rs
- src/protocols/minecraft/protocol/java.rs
- src/protocols/minecraft/protocol/mod.rs
- src/protocols/minecraft/types.rs
- src/socket.rs
> Fix Minecraft Java query not being able to specify a hostname

- .github/labeler.yml
- .github/workflows/labeler.yml
> Add github PR labeler

- CONTRIBUTING.md
> Fix rule 3 example not following rule 2

- .github/dependabot.yml
This PR introduces Dependabot configuration to the project, aiming to streamline the dependency management process and ensure that the workspace is always up-to-date with the latest security patches and bug fixes.
Efficiency:
Automating the process of dependency updates eliminates the manual overhead and helps focus on the repo without worrying about outdated dependencies.
Reliability:
Dependabot's automated PRs make it easier to catch and address potential compatibility issues faster and more reliably than manual oversight.
Up-to-Date Dependencies:
With Dependabot, It can ensure our dependencies are always current, which can improve the lib performance and stability.
> Add dependabot for PRs about dep updates

- crates/lib/src/protocols/unreal2/protocol.rs
- crates/lib/src/protocols/unreal2/types.rs
Closes #146.
I added the new field on the info struct, but I made it `Option` as to indicate if the `GamePassword` rule was found or not, I still have to query a few server as yet I haven't found one that sends it.
I think those that do not send it are passwordless, so its possible to remove the Option.
This is a draft as I still have to check said things.
> feat(unreal2): Add password rule check

- CHANGELOG.md
- crates/lib/examples/minecraft.rs
- crates/lib/src/games/definitions.rs
- crates/lib/src/games/minecraft/mod.rs
- crates/lib/src/games/minecraft/protocol/bedrock.rs
- crates/lib/src/games/minecraft/protocol/java.rs
- crates/lib/src/games/minecraft/protocol/legacy_v1_4.rs
- crates/lib/src/games/minecraft/protocol/legacy_v1_6.rs
- crates/lib/src/games/minecraft/protocol/legacy_vb1_8.rs
- crates/lib/src/games/minecraft/protocol/mod.rs
- crates/lib/src/games/minecraft/types.rs
- crates/lib/src/games/mod.rs
- crates/lib/src/protocols/minecraft/mod.rs
- crates/lib/src/protocols/mod.rs
- crates/lib/src/protocols/types.rs
Closes #119 without addressing the 'proprietary' word rename.
> Move minecraft protocol to games.

- crates/lib/src/games/savage2/mod.rs
- crates/lib/src/games/theship/mod.rs
- crates/lib/src/games/theship/protocol.rs
- crates/lib/src/games/theship/types.rs
Same as #171 but for `The Ship`.
> chore: extract the ship into multiple files

- crates/lib/src/games/ffow/mod.rs
- crates/lib/src/games/ffow/protocol.rs
- crates/lib/src/games/ffow/types.rs
Same as https://github.com/gamedig/rust-gamedig/pull/171 but for `FFOW`.
> chore: extract ffow into multiple files

- Cargo.toml
> Remove unused manifest key

- crates/lib/src/games/eco/protocol.rs
- crates/lib/src/http.rs
Great stuff by @Douile.
Initially done for ASA support, but I've decided to firstly merge this to keep things separated.
> feat: add per-request headers option

- GAMES.md
- crates/lib/CHANGELOG.md
- crates/lib/src/games/definitions.rs
- crates/lib/src/games/valve.rs
This works on a server but reports the app id as being `0`, will have to confirm if this is usual game behavior or an exception with other servers.
> feat: add arma reforger support

- SERVICES.md
- crates/lib/CHANGELOG.md
- crates/lib/examples/teamfortress2.rs
- crates/lib/src/services/minetest_master_server/mod.rs
- crates/lib/src/services/minetest_master_server/service.rs
- crates/lib/src/services/minetest_master_server/types.rs
- crates/lib/src/services/mod.rs
Inspired by [Node-GameDig#573](https://github.com/gamedig/node-gamedig/pull/573).
> feat: add minetest master server service
